name: GitHub Actions Demo
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: npm ci
      - name: Lint
        uses: npm run lint
